name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
    - uses: actions/checkout@v2
    - name: my-step
      run: chmod +x ci/build-app.sh && ci/build-app.sh
    - name: unit-step
      run: ci/unit-test-app.sh
    - name: Upload repo
      uses: actions/upload-artifact@v2
      with:
        name: code
        path: .