name: Java CI
on: push
jobs:
  job-1:
    name: Clone-down
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
  job-2:
    needs: Clone-down
    name: Test
    steps:
    - uses: actions/checkout@v2
    - name: my-step
      run: chmod +x ci/build-app.sh && ci/build-app.sh
    - name: unit-step
      run: ci/unit-test-app.sh
  job-3:
    needs: Clone-down
    name: Build
    uses: actions/upload-artifact@v2
    with:
      name: code
      path: .